# Generated by Django 4.2.7 on 2024-05-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_organization_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='rang',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень в иерархии'),
        ),
    ]
