# Generated by Django 4.2.7 on 2024-05-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_organization_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type_of_organization',
            field=models.CharField(default='factory', max_length=15, verbose_name='Тип организации'),
        ),
    ]
