# Generated by Django 4.2.7 on 2024-05-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_organization_type_of_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type_of_organization',
            field=models.CharField(max_length=15, verbose_name='Тип организации'),
        ),
    ]
