# Generated by Django 4.2.7 on 2024-05-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization', verbose_name='Организация'),
        ),
    ]
